from __future__ import annotations

import httpx


class ElevenAgentsClient:
    def __init__(self, api_key: str | None, base_url: str, agent_id: str | None):
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.agent_id = agent_id

    @property
    def configured(self) -> bool:
        return bool(self.api_key and self.agent_id)

    async def summarize(self, query: str, sources: list[dict]) -> dict:
        if not sources:
            return {
                "summary": "No sources available for synthesis.",
                "key_points": ["No sources available"],
            }

        if not self.configured:
            return self._fallback_extract(query=query, sources=sources)

        headers = {
            "xi-api-key": self.api_key,
            "Content-Type": "application/json",
        }
        payload = {
            "query": query,
            "instructions": {
                "style": "concise factual research summary",
                "require_citations": True,
            },
            "sources": [
                {
                    "title": item.get("title", "Untitled"),
                    "url": item.get("url", ""),
                    "content": (item.get("content") or item.get("snippet") or "")[:2400],
                }
                for item in sources[:8]
            ],
        }

        endpoint = f"{self.base_url}/convai/agents/{self.agent_id}/research/summarize"

        try:
            async with httpx.AsyncClient(timeout=45) as client:
                response = await client.post(endpoint, headers=headers, json=payload)
                response.raise_for_status()
                data = response.json()

            summary = data.get("summary") or data.get("text") or ""
            key_points = data.get("key_points") or data.get("highlights") or []
            if isinstance(key_points, str):
                key_points = [key_points]

            return {
                "summary": summary or "No summary generated by ElevenAgents.",
                "key_points": key_points,
            }
        except Exception:
            return self._fallback_extract(query=query, sources=sources)

    def _fallback_extract(self, query: str, sources: list[dict]) -> dict:
        bullets = []
        for item in sources[:5]:
            title = item.get("title", "Untitled")
            snippet = (item.get("content") or item.get("snippet") or "")[:180]
            bullets.append(f"{title}: {snippet}")

        return {
            "summary": "\n".join(bullets) if bullets else f"No summary available for: {query}",
            "key_points": [f"Reviewed {len(sources)} sources", "ElevenAgents not fully configured or unavailable"],
        }
